// <auto-generated />
using System;
using AgriForecast.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriForecast.Infrastructure.Migrations
{
    [DbContext(typeof(AgriForecastDbContext))]
    [Migration("20260704100335_AddMacroSeriesPoint")]
    partial class AddMacroSeriesPoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriForecast.Domain.Entities.CommodityAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique()
                        .HasDatabaseName("UX_CommodityAliases_AliasGlobal")
                        .HasFilter("[Source] IS NULL");

                    b.HasIndex("CropId");

                    b.HasIndex("Alias", "Source")
                        .IsUnique()
                        .HasDatabaseName("UX_CommodityAliases_AliasSource")
                        .HasFilter("[Source] IS NOT NULL");

                    b.HasIndex("Alias", "Source", "IsActive")
                        .HasDatabaseName("IX_CommodityAliases_AliasSourceActive");

                    b.ToTable("CommodityAliases");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CropCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalProductId")
                        .HasColumnType("int");

                    b.Property<int?>("GrowthPeriodDays")
                        .HasColumnType("int");

                    b.Property<int?>("HarvestWindowDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantingSeason")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.CropPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EconomicCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EconomicCenterId");

                    b.HasIndex("CropId", "EconomicCenterId", "Month")
                        .IsUnique();

                    b.ToTable("CropPrices");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.DefaultSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Crop_Code")
                        .HasColumnType("int");

                    b.Property<int?>("Crop_Padding")
                        .HasColumnType("int");

                    b.Property<string>("Crop_Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Eco_Code")
                        .HasColumnType("int");

                    b.Property<int?>("Eco_Padding")
                        .HasColumnType("int");

                    b.Property<string>("Eco_Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Mkt_Code")
                        .HasColumnType("int");

                    b.Property<int?>("Mkt_Padding")
                        .HasColumnType("int");

                    b.Property<string>("Mkt_Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DefaultSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crop_Code = 1,
                            Crop_Padding = 8,
                            Crop_Prefix = "CROP",
                            Eco_Code = 1,
                            Eco_Padding = 8,
                            Eco_Prefix = "ECO",
                            Mkt_Code = 7,
                            Mkt_Padding = 8,
                            Mkt_Prefix = "MKT"
                        });
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.EconomicCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MarketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.ToTable("EconomicCenters");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.EconomicIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndicatorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "IndicatorCode")
                        .IsUnique();

                    b.ToTable("EconomicIndicators");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.FestivalCalendarEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("FestivalKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("bit");

                    b.Property<int>("LeadUpDays")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("FestivalKey", "Date")
                        .IsUnique();

                    b.ToTable("FestivalCalendarEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002015"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2015, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2015"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002015"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2015, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2015"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002015"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2015, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2015"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002015"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002016"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2016, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2016"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002016"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2016, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2016"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002016"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2016, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2016"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002016"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2016, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002017"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2017, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2017"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002017"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2017, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2017"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002017"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2017, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2017"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002017"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2017, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002018"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2018, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2018"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002018"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2018, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2018"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002018"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2018, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2018"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002018"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002019"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2019, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2019"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002019"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2019, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2019"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002019"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2019, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2019"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002019"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002020"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2020"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002020"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2020"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002020"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2020"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002020"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002021"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2021, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2021"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002021"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2021, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2021"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002021"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2021, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2021"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002021"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002022"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2022"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002022"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2022, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2022"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002022"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2022, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2022"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002022"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002023"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2023, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2023"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002023"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2023, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2023"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002023"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2023"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002023"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002024"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2024"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002024"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2024"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002024"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2024"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002024"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002025"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2025"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002025"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2025"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002025"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2025"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002025"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002026"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2026"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002026"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = false,
                            LeadUpDays = 0,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2026"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002026"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Department of Government Printing, Sri Lanka — annual holiday gazette 2026"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002026"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002027"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2027, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = true,
                            LeadUpDays = 14
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002027"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2027, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = true,
                            LeadUpDays = 0
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002027"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2027, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = true,
                            LeadUpDays = 14
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002027"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2027, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002028"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2028, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = true,
                            LeadUpDays = 14
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002028"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2028, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = true,
                            LeadUpDays = 0
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002028"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2028, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = true,
                            LeadUpDays = 14
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002028"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2028, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002029"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2029, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = true,
                            LeadUpDays = 14
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002029"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2029, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = true,
                            LeadUpDays = 0
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002029"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2029, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = true,
                            LeadUpDays = 14
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002029"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2029, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a013-000000002030"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2030, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = true,
                            LeadUpDays = 14
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-a014-000000002030"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2030, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "AVURUDU",
                            IsProvisional = true,
                            LeadUpDays = 0
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-7014-000000002030"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2030, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "THAI_PONGAL",
                            IsProvisional = true,
                            LeadUpDays = 14
                        },
                        new
                        {
                            Id = new Guid("c3f30001-0000-0000-c025-000000002030"),
                            CreatedAtUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2030, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FestivalKey = "CHRISTMAS",
                            IsProvisional = false,
                            LeadUpDays = 14,
                            Source = "Fixed Gregorian date (Dec 25)"
                        });
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.IngestionWatermark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("LastObservedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastSuccessUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .IsUnique();

                    b.ToTable("IngestionWatermarks");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.MacroSeriesPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublishedAtImputed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("SeriesCode", "PublishedAt");

                    b.HasIndex("SeriesCode", "ReferenceDate");

                    b.HasIndex("SeriesCode", "ReferenceDate", "PublishedAt")
                        .IsUnique();

                    b.ToTable("MacroSeriesPoints");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MarketType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode")
                        .IsUnique();

                    b.ToTable("Markets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2a20001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Matale",
                            IsActive = true,
                            MarketCode = "MKT00000001",
                            MarketType = 2,
                            Name = "Dambulla Dedicated Economic Centre",
                            UpdatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2a20001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Badulla",
                            IsActive = true,
                            MarketCode = "MKT00000002",
                            MarketType = 2,
                            Name = "Keppetipola Dedicated Economic Centre",
                            UpdatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2a20001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Anuradhapura",
                            IsActive = true,
                            MarketCode = "MKT00000003",
                            MarketType = 2,
                            Name = "Thambuttegama Dedicated Economic Centre",
                            UpdatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2a20001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Colombo",
                            IsActive = true,
                            MarketCode = "MKT00000004",
                            MarketType = 0,
                            Name = "Pettah (HARTI wholesale)",
                            UpdatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2a20001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Colombo",
                            IsActive = true,
                            MarketCode = "MKT00000005",
                            MarketType = 1,
                            Name = "Narahenpita (HARTI retail)",
                            UpdatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2a20001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MarketCode = "MKT00000006",
                            MarketType = 3,
                            Name = "CBSL national average (pseudo-market)",
                            UpdatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.MarketPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EconomicCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExternalProductId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ExternalProductId", "PriceDate")
                        .IsUnique();

                    b.ToTable("MarketPrices");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.PolicyFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("PolicyType")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom");

                    b.ToTable("PolicyFlags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Government banned imports of chemical fertilisers, pesticides and weedicides, forcing a nationwide shift to organic farming. Cut yields sharply across paddy and vegetables, pushing harvest-time prices up.",
                            Direction = 1,
                            EffectiveFrom = new DateTime(2021, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2021, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 1,
                            ReferenceUrl = "https://en.wikipedia.org/wiki/2021%E2%80%932022_Sri_Lankan_political_crisis",
                            Source = "Government of Sri Lanka",
                            Title = "Chemical fertiliser & agrochemical import ban"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reinstated fertiliser support for the 2022/23 Maha season via direct cash and subsidised fertiliser to paddy farmers, easing input costs and partially recovering yields.",
                            Direction = -1,
                            EffectiveFrom = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2023, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 5,
                            Source = "Ministry of Agriculture, Sri Lanka",
                            Title = "Aswesuma / fertiliser cash subsidy for paddy farmers"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Introduction of a transparent monthly fuel pricing formula. Transport/diesel cost feeds into farm-gate to wholesale transport margins; ongoing, still in effect.",
                            Direction = 0,
                            EffectiveFrom = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 6,
                            Source = "Ceylon Petroleum Corporation",
                            Title = "Monthly fuel price formula (CPC pricing formula)"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Import controls / suspension on big onions and potatoes to protect local growers around the harvest window, tightening domestic supply and lifting prices.",
                            Direction = 1,
                            EffectiveFrom = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 1,
                            Source = "Department of Imports and Exports Control, Sri Lanka",
                            Title = "Big onion & potato import restrictions"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Consumer Affairs Authority imposed maximum retail prices (price ceilings) on Nadu, Samba and Keeri Samba rice to curb retail inflation during the economic crisis.",
                            Direction = -1,
                            EffectiveFrom = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 3,
                            Source = "Consumer Affairs Authority, Sri Lanka",
                            Title = "Maximum retail price on rice varieties"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Continued subsidised fertiliser distribution to paddy farmers for the 2023/24 Maha season, supporting normalised yields; still in effect.",
                            Direction = -1,
                            EffectiveFrom = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 5,
                            Source = "Ministry of Agriculture, Sri Lanka",
                            Title = "Fertiliser subsidy scheme continuation (2023/24)"
                        });
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.PriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ArrivalsKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("AsOfUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExternalCommodityId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalCommodityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsUnitConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("ObservedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("RetailPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("UnitConversionFactor")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("UnitRaw")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("WholesalePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("MarketId", "CropId", "ObservedDate")
                        .HasDatabaseName("IX_PriceObservations_MarketCropDate");

                    b.HasIndex("MarketId", "ExternalCommodityId", "ObservedDate", "Source")
                        .IsUnique()
                        .HasDatabaseName("UX_PriceObservations_MarketCommodityIdDateSource")
                        .HasFilter("[ExternalCommodityId] IS NOT NULL");

                    b.HasIndex("MarketId", "ExternalCommodityName", "ObservedDate", "Source")
                        .IsUnique()
                        .HasDatabaseName("UX_PriceObservations_MarketCommodityNameDateSource")
                        .HasFilter("[ExternalCommodityId] IS NULL");

                    b.ToTable("PriceObservations");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.WeatherRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AvgTemperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalRainfall")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("WeatherRecords");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.CommodityAlias", b =>
                {
                    b.HasOne("AgriForecast.Domain.Entities.Crop", null)
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.CropPrice", b =>
                {
                    b.HasOne("AgriForecast.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriForecast.Domain.Entities.EconomicCenter", "EconomicCenter")
                        .WithMany()
                        .HasForeignKey("EconomicCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("EconomicCenter");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.EconomicCenter", b =>
                {
                    b.HasOne("AgriForecast.Domain.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.PriceObservation", b =>
                {
                    b.HasOne("AgriForecast.Domain.Entities.Crop", null)
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriForecast.Domain.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
