// <auto-generated />
using System;
using AgriForecast.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriForecast.Infrastructure.Migrations
{
    [DbContext(typeof(AgriForecastDbContext))]
    [Migration("20260219182649_add market price")]
    partial class addmarketprice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriForecast.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CropCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.DefaultSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Crop_Code")
                        .HasColumnType("int");

                    b.Property<int?>("Crop_Padding")
                        .HasColumnType("int");

                    b.Property<string>("Crop_Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Eco_Code")
                        .HasColumnType("int");

                    b.Property<int?>("Eco_Padding")
                        .HasColumnType("int");

                    b.Property<string>("Eco_Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DefaultSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crop_Code = 1,
                            Crop_Padding = 8,
                            Crop_Prefix = "CROP",
                            Eco_Code = 1,
                            Eco_Padding = 8,
                            Eco_Prefix = "ECO"
                        });
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.EconomicCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EconomicCenters");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.MarketPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CropId")
                        .HasColumnType("int");

                    b.Property<int?>("EconomicCenterId")
                        .HasColumnType("int");

                    b.Property<int>("ExternalProductId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ExternalProductId", "PriceDate")
                        .IsUnique();

                    b.ToTable("MarketPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
