// <auto-generated />
using System;
using AgriForecast.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriForecast.Infrastructure.Migrations
{
    [DbContext(typeof(AgriForecastDbContext))]
    [Migration("20260630141422_AddPolicyFlag")]
    partial class AddPolicyFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriForecast.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CropCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalProductId")
                        .HasColumnType("int");

                    b.Property<int?>("GrowthPeriodDays")
                        .HasColumnType("int");

                    b.Property<int?>("HarvestWindowDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantingSeason")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.CropPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EconomicCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EconomicCenterId");

                    b.HasIndex("CropId", "EconomicCenterId", "Month")
                        .IsUnique();

                    b.ToTable("CropPrices");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.DefaultSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Crop_Code")
                        .HasColumnType("int");

                    b.Property<int?>("Crop_Padding")
                        .HasColumnType("int");

                    b.Property<string>("Crop_Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Eco_Code")
                        .HasColumnType("int");

                    b.Property<int?>("Eco_Padding")
                        .HasColumnType("int");

                    b.Property<string>("Eco_Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DefaultSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crop_Code = 1,
                            Crop_Padding = 8,
                            Crop_Prefix = "CROP",
                            Eco_Code = 1,
                            Eco_Padding = 8,
                            Eco_Prefix = "ECO"
                        });
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.EconomicCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EconomicCenters");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.EconomicIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndicatorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "IndicatorCode")
                        .IsUnique();

                    b.ToTable("EconomicIndicators");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.MarketPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EconomicCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExternalProductId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ExternalProductId", "PriceDate")
                        .IsUnique();

                    b.ToTable("MarketPrices");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.PolicyFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("PolicyType")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom");

                    b.ToTable("PolicyFlags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Government banned imports of chemical fertilisers, pesticides and weedicides, forcing a nationwide shift to organic farming. Cut yields sharply across paddy and vegetables, pushing harvest-time prices up.",
                            Direction = 1,
                            EffectiveFrom = new DateTime(2021, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2021, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 1,
                            ReferenceUrl = "https://en.wikipedia.org/wiki/2021%E2%80%932022_Sri_Lankan_political_crisis",
                            Source = "Government of Sri Lanka",
                            Title = "Chemical fertiliser & agrochemical import ban"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reinstated fertiliser support for the 2022/23 Maha season via direct cash and subsidised fertiliser to paddy farmers, easing input costs and partially recovering yields.",
                            Direction = -1,
                            EffectiveFrom = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2023, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 5,
                            Source = "Ministry of Agriculture, Sri Lanka",
                            Title = "Aswesuma / fertiliser cash subsidy for paddy farmers"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Introduction of a transparent monthly fuel pricing formula. Transport/diesel cost feeds into farm-gate to wholesale transport margins; ongoing, still in effect.",
                            Direction = 0,
                            EffectiveFrom = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 6,
                            Source = "Ceylon Petroleum Corporation",
                            Title = "Monthly fuel price formula (CPC pricing formula)"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Import controls / suspension on big onions and potatoes to protect local growers around the harvest window, tightening domestic supply and lifting prices.",
                            Direction = 1,
                            EffectiveFrom = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 1,
                            Source = "Department of Imports and Exports Control, Sri Lanka",
                            Title = "Big onion & potato import restrictions"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Consumer Affairs Authority imposed maximum retail prices (price ceilings) on Nadu, Samba and Keeri Samba rice to curb retail inflation during the economic crisis.",
                            Direction = -1,
                            EffectiveFrom = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 3,
                            Source = "Consumer Affairs Authority, Sri Lanka",
                            Title = "Maximum retail price on rice varieties"
                        },
                        new
                        {
                            Id = new Guid("a1f1c001-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Continued subsidised fertiliser distribution to paddy farmers for the 2023/24 Maha season, supporting normalised yields; still in effect.",
                            Direction = -1,
                            EffectiveFrom = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyType = 5,
                            Source = "Ministry of Agriculture, Sri Lanka",
                            Title = "Fertiliser subsidy scheme continuation (2023/24)"
                        });
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.WeatherRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AvgTemperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalRainfall")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("WeatherRecords");
                });

            modelBuilder.Entity("AgriForecast.Domain.Entities.CropPrice", b =>
                {
                    b.HasOne("AgriForecast.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriForecast.Domain.Entities.EconomicCenter", "EconomicCenter")
                        .WithMany()
                        .HasForeignKey("EconomicCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("EconomicCenter");
                });
#pragma warning restore 612, 618
        }
    }
}
