<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="13.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Requests\Crop\Quaries\GetOneByCode\" />
      <Folder Include="Requests\Weather\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AgriForecast.Domain\AgriForecast.Domain.csproj" />
    </ItemGroup>

</Project>
